version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build: .
    command: npm test
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
